plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - query.md
  - object.md
  - scalar.md
  - mutation.md
  - enum.md
  - interface.md
  - locationapi/query.md
  - locationapi/object.md
  - locationapi/scalar.md
  - locationapi/mutation.md
  - locationapi/enum.md
  - locationapi/interface.md
theme: jekyll-theme-cayman
