plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - query.md
  - object.md
  - scalar.md
  - mutation.md
  - enum.md
  - interface.md
theme: jekyll-theme-cayman
