plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.html
  - peopleapi/query.md
  - peopleapi/object.md
  - peopleapi/scalar.md
  - peopleapi/mutation.md
  - peopleapi/enum.md
  - peopleapi/interface.md
  - locationapi/query.md
  - locationapi/object.md
  - locationapi/scalar.md
  - locationapi/mutation.md
  - locationapi/enum.md
  - locationapi/interface.md
  - eventsapi/query.md
  - eventsapi/object.md
  - eventsapi/scalar.md
  - eventsapi/mutation.md
  - eventsapi/enum.md
  - eventsapi/interface.md
  - peopleexapi/query.md
  - peopleexapi/object.md
  - peopleexapi/scalar.md
  - peopleexapi/mutation.md
  - peopleexapi/enum.md
  - peopleexapi/interface.md
#theme: jekyll-theme-cayman

theme: jekyll-theme-leap-day