plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - peopleapi/query.md
  - peopleapi/object.md
  - peopleapi/scalar.md
  - peopleapi/mutation.md
  - peopleapi/enum.md
  - peopleapi/interface.md
  - locationapi/query.md
  - locationapi/object.md
  - locationapi/scalar.md
  - locationapi/mutation.md
  - locationapi/enum.md
  - locationapi/interface.md
theme: jekyll-theme-cayman
