plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - peopleapi/query.md
  - peopleapi/object.md
  - peopleapi/scalar.md
  - peopleapi/mutation.md
  - peopleapi/enum.md
  - peopleapi/interface.md
theme: jekyll-theme-cayman
